# Generated by Django 4.2 on 2025-02-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.FileField(blank=True, null=True, upload_to='media/listening/')),
                ('reading', models.FileField(blank=True, null=True, upload_to='media/reading/')),
                ('writing', models.FileField(blank=True, null=True, upload_to='media/writing/')),
                ('speaking', models.FileField(blank=True, null=True, upload_to='media/speaking/')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
